# Generated by Django 3.2.16 on 2026-01-10 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_comment_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='comment_count',
        ),
    ]
